language: python
os:
  - linux
python:
  - "3.6"
jdk:
  - oraclejdk8
script:
  - pip install -r requirements/web.txt
  - pip install -r requirements/test.txt
  - nosetests --with-coverage --cover-package=references
