language: python
os:
  - linux
python:
  - "3.6"
jdk:
  - oraclejdk8
script:
  - pip install coverage
  - pip install nose
  - pip install -r requirements.txt
  - nosetests --with-coverage --cover-package=references
