language: python
cache: pip
os:
  - linux
python:
  - "3.6"
jdk:
  - oraclejdk8
script:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
  - ./lintstats.sh
  - pipenv run nose2 --with-coverage
after_success:
  - coveralls
