version: '3'

services:
  references-agent:
    build:
      context: .
      dockerfile: Dockerfile-agent
    container_name: references-agent
    environment:
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      CLOUDWATCH_ENDPOINT: "https://references-test-localstack:4582"
      DYNAMODB_ENDPOINT: "https://references-test-localstack:4569"
      KINESIS_ENDPOINT: "https://references-test-localstack:4568"
      KINESIS_VERIFY: "false"
      DYNAMODB_VERIFY: "false"
      CLOUDWATCH_VERIFY: "false"
      EXTRACTION_ENDPOINT: "http://references-api:8000"
      LOGLEVEL: 10
      LOGFILE: "/var/log/references-agent-processor.log"
      MODE: "test"
      JAVA_FLAGS: "-Dcom.amazonaws.sdk.disableCertChecking"
      AWS_CBOR_DISABLE: "true"
      INSTANCE_CREDENTIALS: "false"
      AGENT_CHECKPOINT_FREQ: "1"
      AGENT_SLEEP_SECONDS: "1"
    networks:
      - references-test
    depends_on:
      - references-test-localstack
      - references-worker
      - references-api
  references-cermine:
    build:
      context: ./extractors/cermine
      dockerfile: Dockerfile
    container_name: references-cermine
    networks:
      - references-test
  references-refextract:
    build:
      context: ./extractors/refextract
      dockerfile: Dockerfile
    container_name: references-refextract
    networks:
      - references-test
  references-test-redis:
    image: redis
    container_name: references-test-redis
    networks:
      - references-test
  references-test-localstack:
    image: atlassianlabs/localstack
    container_name: references-test-localstack
    networks:
      - references-test
    ports:
      - "5582:4582"
      - "5568:4568"
      - "5569:4569"
    environment:
      USE_SSL: 'true'
      DEBUG: 'true'
  references-worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    environment:
      REDIS_ENDPOINT: "references-test-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      CLOUDWATCH_ENDPOINT: "https://references-test-localstack:4582"
      DYNAMODB_ENDPOINT: "https://references-test-localstack:4569"
      CERMINE_ENDPOINT: "http://references-cermine:8000"
      REFEXTRACT_ENDPOINT: "http://references-refextract:8000"
      DYNAMODB_VERIFY: "false"
      CLOUDWATCH_VERIFY: "false"
      INSTANCE_CREDENTIALS: "false"
      LOGLEVEL: 10
    networks:
      - references-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pdfs:/tmp/pdfs
    depends_on:
      - references-test-redis
      - references-test-localstack
      - references-cermine
      - references-refextract
  references-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: references-api
    environment:
      REDIS_ENDPOINT: "references-test-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      CLOUDWATCH_ENDPOINT: "https://references-test-localstack:4582"
      DYNAMODB_ENDPOINT: "https://references-test-localstack:4569"
      CERMINE_ENDPOINT: "http://references-cermine:8000"
      REFEXTRACT_ENDPOINT: "http://references-refextract:8000"
      DYNAMODB_VERIFY: "false"
      CLOUDWATCH_VERIFY: "false"
      INSTANCE_CREDENTIALS: "false"
      LOGLEVEL: 10
    ports:
      - "8001:8000"
    networks:
      - references-test
    depends_on:
      - references-test-redis
      - references-test-localstack
      - references-worker
      - references-cermine
      - references-refextract


networks:
  references-test:
