version: '3'

services:
  references-agent:
    build:
      context: .
      dockerfile: Dockerfile-agent
    container_name: references-agent
    environment:
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      KINESIS_ENDPOINT: "https://references-test-localstack:4568"
      KINESIS_VERIFY: "false"
      KINESIS_START_TYPE: "TRIM_HORIZON"
      LOGLEVEL: 10
      REDIS_MASTER_SERVICE_HOST: references-test-redis
      REDIS_MASTER_SERVICE_PORT: 6379
      GROBID_ENDPOINT: "http://references-grobid:8080"
      REFEXTRACT_ENDPOINT: "http://references-refextract:8000"
      CERMINE_ENDPOINT: "http://references-cermine:8000"
      SCIENCEPARSE_ENDPOINT: "http://references-scienceparse:8000"

    networks:
      - references-test
    depends_on:
      - references-test-localstack

  references-cermine:
    build:
      context: ./extractors/cermine
      dockerfile: Dockerfile
    container_name: references-cermine
    networks:
      - references-test

  references-refextract:
    build:
      context: ./extractors/refextract
      dockerfile: Dockerfile
    container_name: references-refextract
    networks:
      - references-test

  references-grobid:
    image: arxiv/grobid
    container_name: references-grobid
    networks:
      - references-test

  references-scienceparse:
    image: arxiv/scienceparse
    container_name: references-scienceparse
    networks:
      - references-test

  references-test-redis:
    image: redis
    container_name: references-test-redis
    networks:
      - references-test

  references-test-localstack:
    image: atlassianlabs/localstack
    container_name: references-test-localstack
    networks:
      - references-test
    ports:
      - "5582:4582"
      - "5568:4568"
      - "5569:4569"
    environment:
      USE_SSL: 'true'
      DEBUG: 'true'

  references-worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    environment:
      REDIS_ENDPOINT: "references-test-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      CERMINE_ENDPOINT: "http://references-cermine:8000"
      REFEXTRACT_ENDPOINT: "http://references-refextract:8000"
      GROBID_ENDPOINT: "http://references-grobid:8080"
      SCIENCEPARSE_ENDPOINT: "http://references-scienceparse:8000"
      LOGLEVEL: 10
    networks:
      - references-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pdfs:/tmp/pdfs
    depends_on:
      - references-test-redis
      - references-test-localstack
      - references-cermine
      - references-refextract

  references-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: references-api
    environment:
      REDIS_ENDPOINT: "references-test-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      CERMINE_ENDPOINT: "http://references-cermine:8000"
      REFEXTRACT_ENDPOINT: "http://references-refextract:8000"
      GROBID_ENDPOINT: "http://references-grobid:8080"
      SCIENCEPARSE_ENDPOINT: "http://references-scienceparse:8000"
      LOGLEVEL: 10
    ports:
      - "8001:8000"
    networks:
      - references-test
    depends_on:
      - references-test-redis
      - references-test-localstack
      - references-worker
      - references-cermine
      - references-refextract


networks:
  references-test:
