- include_vars: vars/secrets.yml

- name: install python3
  yum:
    name: python35
    state: present

- name: get pip installer
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/usr/src

- name: install pip
  command: python3 /usr/src/get-pip.py

- name: enable epel repos
  yum: name=epel-release state=present

- name: install git
  yum:
    name: git
    state: present

- name: install virtualenv
  pip:
    executable: pip
    name: virtualenv

- name: create app tree
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/reflink
    - /opt/reflink/jars
    - /opt/reflink/bin
    - /opt/reflink/arxiv-reflink

- name: make sure zip/unzip are installed
  yum:
    name:
      - zip
      - unzip
    state: present

- name: unarchive reflink source
  unarchive:
    src: files/reflink.zip
    dest: /opt/reflink/arxiv-reflink
    force: yes

- name: create app virtualenv
  command: virtualenv /opt/reflink/venv --python=python3
  args:
    creates: /opt/reflink/venv

- name: install python dependencies for app
  pip:
    requirements: /opt/reflink/arxiv-reflink/requirements.txt
    virtualenv: /opt/reflink/venv

# - name: copy endpoints config (testing/dev only)
#   copy:
#     src: files/endpoints.json
#     dest: /opt/reflink/endpoints.json

- name: copy secrets
  template:
    src: templates/secrets
    dest: /opt/reflink/secrets

- name: copy Python secrets for webapp
  template:
    src: templates/secrets.py
    dest: /opt/reflink/arxiv-reflink/reflink/secrets.py
