- include_vars: vars/secrets.yml

- name: install python3
  yum:
    name: python35
    state: present

- name: get pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /usr/src


- name: install pip
  command: python3 /usr/src/get-pip.py



# - name: create user
#   user:
#     name: "{{ reflink_user }}"
#     state: present
#     createhome: yes


# - name: make sure yum is up to date
#   yum:
#     name: '*'
#     state: latest
#

- name: enable epel repos
  yum:
    name: epel-release
    state: present


- name: install git
  yum:
    name: git
    state: present


- name: install virtualenv
  pip:
    executable: pip
    name: virtualenv


- name: create app tree
  file:
    path: "{{ item }}"
    state: directory
    #owner: "{{ reflink_user }}"
    #group: "{{ reflink_user }}"
  with_items:
    - /opt/reflink
    - /opt/reflink/jars
    - /opt/reflink/bin


- name: make sure zip/unzip are installed
  yum:
    name:
      - zip
      - unzip
    state: present


- name: unarchive reflink source
  unarchive:
    src: files/reflink.zip
    dest: /opt/reflink
    force: yes
    # creates: /opt/reflink/arxiv-reflink

  #become_user: "{{ reflink_user }}"

- name: create app virtualenv
  command: virtualenv /opt/reflink/venv --python=python3
  args:
    creates: /opt/reflink/venv

  #become_user: "{{ reflink_user }}"

- name: install python dependencies for app
  pip:
    requirements: /opt/reflink/arxiv-reflink/requirements.txt
    virtualenv: /opt/reflink/venv

  #become_user: "{{ reflink_user }}"

- name: copy endpoints config (testing/dev only)
  copy:
    src: files/endpoints.json
    dest: /opt/reflink/endpoints.json

- name: copy secrets
  template:
    src: templates/secrets
    dest: /opt/reflink/secrets

  #become_user: "{{ reflink_user }}"
