- include_vars: vars/vars.yml

- include_vars: vars/secrets.yml
  no_log: yes

- include: install_java8.yml

- name: create  user
  user:
    name: "{{ consumer_user }}"
    state: present
    createhome: yes
  become: yes

- name: make sure yum is up to date
  yum:
    name: '*'
    state: latest
  become: yes

- name: enable epel repos
  yum:
    name: epel-release
    state: present
  become: yes

- name: install git
  yum:
    name: git
    state: present
  become: yes

- include: build_python_from_source.yml

- name: install virtualenv
  pip:
    executable: /opt/bin/pip3.6
    name: virtualenv
  become: yes

- name: create app tree
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consumer_user }}"
    group: "{{ consumer_user }}"
  with_items:
    - /opt/reflink
    - /opt/reflink/jars
    - /opt/reflink/bin
  become: yes

- name: create log file
  file:
    path: /var/log/reflinkconsumer.log
    state: touch
  become: yes

- name: unarchive reflink source
  unarchive:
    src: files/reflink.zip
    dest: /opt/reflink
    creates: /opt/reflink/arxiv-reflink
  become: yes
  become_user: "{{ consumer_user }}"

- name: create app virtualenv
  command: /opt/bin/python3.6 /opt/lib/python3.6/site-packages/virtualenv.py /opt/reflink/venv --python=/opt/bin/python3.6
  args:
    creates: /opt/reflink/venv
  become: yes
  become_user: "{{ consumer_user }}"

- name: install python dependencies for app
  pip:
    requirements: /opt/reflink/arxiv-reflink/requirements.txt
    virtualenv: /opt/reflink/venv
  become: yes
  become_user: "{{ consumer_user }}"

- name: copy startup assets
  copy:
    src: files/{{ item }}
    dest: /opt/reflink/bin/{{ item }}
    owner: "{{ consumer_user }}"
    group: "{{ consumer_user }}"
    mode: "u=rwx,g=r,o=r"
  with_items:
    - consumer.properties
    - start_kcl
  become: yes
  become_user: "{{ consumer_user }}"

- name: copy service script (for Centos/RHEL 7)
  copy:
    src: files/reflink-consumer.service
    dest: /usr/lib/systemd/system/reflink-consumer.service
    mode: 0755
  become: yes
  when: "'vagrant' in group_names"

- name: copy oldschool service script (for AWS AMI, Centos/RHEL <=6)
  copy:
    src: files/reflink-consumer
    dest: /etc/init.d/reflink-consumer
    mode: 0755
  become: yes
  when: "'ec2hosts' in group_names"

- name: get kinesis client library
  git:
    repo: https://github.com/awslabs/amazon-kinesis-client-python.git
    dest: /tmp/amazon-kinesis-client-python
  become: yes
  become_user: "{{ consumer_user }}"

- name: download jars for KCL
  get_url:
    url: http://search.maven.org/remotecontent?filepath={{ item.group }}/{{ item.artifact_id }}/{{ item.version }}/{{ item.artifact_id }}-{{ item.version }}.jar
    dest: /opt/reflink/jars/{{ item.artifact_id }}-{{ item.version }}.jar
  with_items:
    - group: com/amazonaws
      artifact_id: amazon-kinesis-client
      version: 1.7.6
    - group: com/amazonaws
      artifact_id: aws-java-sdk-dynamodb
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-s3
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-kms
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-core
      version: 1.11.151
    - group: org/apache/httpcomponents
      artifact_id: httpclient
      version: 4.5.2
    - group: org/apache/httpcomponents
      artifact_id: httpcore
      version: 4.4.4
    - group: commons-codec
      artifact_id: commons-codec
      version: 1.9
    - group: software/amazon/ion
      artifact_id: ion-java
      version: 1.0.2
    - group: com/fasterxml/jackson/core
      artifact_id: jackson-databind
      version: 2.6.6
    - group: com/fasterxml/jackson/core
      artifact_id: jackson-databind
      version: 2.6.6
    - group: com/fasterxml/jackson/core
      artifact_id: jackson-annotations
      version: 2.6.0
    - group: com/fasterxml/jackson/core
      artifact_id: jackson-core
      version: 2.6.6
    - group: com/fasterxml/jackson/dataformat
      artifact_id: jackson-dataformat-cbor
      version: 2.6.6
    - group: joda-time
      artifact_id: joda-time
      version: 2.8.1
    - group: com/amazonaws
      artifact_id: jmespath-java
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-kinesis
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-cloudwatch
      version: 1.11.151
    - group: com/google/guava
      artifact_id: guava
      version: 18.0
    - group: com/google/protobuf
      artifact_id: protobuf-java
      version: 2.6.1
    - group: commons-lang
      artifact_id: commons-lang
      version: 2.6
    - group: commons-logging
      artifact_id: commons-logging
      version: 1.1.3
  become: yes
  become_user: "{{ consumer_user }}"

- name: copy secrets
  template:
    src: templates/secrets
    dest: /opt/reflink/secrets
  become: yes
  become_user: "{{ consumer_user }}"

- name: enable and start service
  service:
    name: reflink-consumer
    enabled: yes
    state: started
  become: yes
