- name: make sure that docker-py is installed
  pip: name=docker-py state=latest executable=/usr/local/bin/pip

- name: make sure docker is installed
  yum: name=docker state=latest

- name: create worker user
  user: name=reflinkworker groups=docker state=present

- name: give worker user ownership
  file:
    path: /opt/reflink
    owner: reflinkworker
    recurse: yes

- name: give worker ownership of log file
  file:
    path: /var/log/reflink-worker.log
    owner: reflinkworker

- name: copy cermine jar
  copy:
    src: files/cermine-impl-1.12-jar-with-dependencies.jar
    dest: /opt/reflink/arxiv-reflink/docker/cermine/cermine-impl-1.12-jar-with-dependencies.jar

- name: build cermine docker image
  docker_image:
     path: /opt/reflink/arxiv-reflink/docker/cermine
     name: mattbierbaum/cermine

- name: prepare autotex docker
  command: ./prepare-autotex.sh
  args:
    chdir: /opt/reflink/arxiv-reflink/docker/autotex

- name: build autotex docker image
  docker_image:
    path: /opt/reflink/arxiv-reflink/docker/autotex
    name: mattbierbaum/autotex

- name: copy startup assets
  copy:
    src: files/start_worker
    dest: /opt/reflink/bin/start_worker
    mode: "u=rwx,g=r,o=r"

- name: copy oldschool service script (for AWS AMI, Centos/RHEL <=6)
  copy:
    src: files/reflink-worker
    dest: /etc/init.d/reflink-worker
    mode: 0755

  # when: "'ec2hosts' in group_names"

- name: create log file
  file:
    path: /var/log/reflink-worker.log
    state: touch

- name: enable and start service
  service:
    name: reflink-worker
    enabled: yes
    state: restarted
